### PR TITLE
Update pnor for SBE dd2.1 images

### PR DESCRIPTION
**Pull request by Shakeebbk**
Include SBE dd2.1 images in the SBE partition

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/pnor/78)

### CODE REVIEW

**Comment by sgupta2m** [comment]
OK to test

**Comment by sgupta2m** [comment]
retest this please.

**Comment by sgupta2m** [comment]
retest this please

**Comment by sgupta2m** [comment]
OK to test

**Comment by pragupta** [comment]
retest this please

**Comment by sgupta2m** [comment]
Tested it with sbe DD2.1 image in partitionan , system comes to runtime

**Pull request merged**
