### PR TITLE
SBE image install

### PR DESCRIPTION
**Pull request by Shakeebbk**
These changes would update pnor header, add rings and ecc to the SBE image.
This would break the current op-build. Need a corresponding op-build commit which is also up in the queue.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/pnor/61)

### CODE REVIEW

**Comment by sannerd** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[update_image.pl, line 61 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVp47HkkjGKIOpG8Md:-KgVp47HkkjGKIOpG8Me:b-n9pmvr) ([raw file](https://github.com/open-power/pnor/blob/52b1b91ea5ea7651688802f72d168139c29c4780/update_image.pl#L61)):*
> ```Prolog
>         shift;
>     }
>     elsif (/^-sbe_binary_filename/i){
> ```

Keep in mind that this same script needs to support P8 systems as well as P9.   I don't see the rest of the code handling P8?

---

*[update_image.pl, line 175 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVpPXlIUQafNsLFtyk:-KgVpPXmAPIZeqWIlH8Q:b-uxo6ms) ([raw file](https://github.com/open-power/pnor/blob/529a0bac8b6ca6edc918a76c1825ce8bfc78bd18/update_image.pl#L175)):*
> ```Prolog
> #SBE image prep
> if ($release eq "p9") {
>     foreach (@ec_levels) {
> ```

For future proofing, you might want to let the SBE bin output dictate the necessary EC levels?   In otherwords out of the SBE compile emit the EC levels that are required and have this script read them in?

---

*[update_image.pl, line 186 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVoWP_Rgy-oyJmqmro:-KgVoWPavM4GM6RAmhdj:b-iqkr0t) ([raw file](https://github.com/open-power/pnor/blob/529a0bac8b6ca6edc918a76c1825ce8bfc78bd18/update_image.pl#L186)):*
> ```Prolog
>         run_command("cat $scratch_dir/${stop_basename}.bin >> $scratch_dir/${stop_basename}.hdr.bin");
> 
>         run_command("$hb_image_dir/buildSbePart.pl --sbeOutBin $scratch_dir/$sbe_out_image --ecImg_$ec_val{$_} $scratch_dir/$stop_basename.hdr.bin");
> ```

This part should be outside of the for loop -- the buildSbePart script takes input of ALL supported EC levels for a chip and creates one PNOR partition.   Note that the SBE partition size will probably have to grow to 512K to accommodate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/pnor/61)*

**Comment by wghoffa** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[update_image.pl, line 177 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVqv26AIkLjWgdCQQc:-KgVqv26AIkLjWgdCQQd:b-suybko) ([raw file](https://github.com/open-power/pnor/blob/529a0bac8b6ca6edc918a76c1825ce8bfc78bd18/update_image.pl#L177)):*
> nimbus_sbe.img

You probably need to add the EC level on to this? Otherwise aren't you going to overwrite the first EC with the second as the filenames match?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/pnor/61)*

**Comment by Shakeebbk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[update_image.pl, line 61 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVp47HkkjGKIOpG8Md:-KgcEWC2EIUaoLSQRLqM:bunnx7f) ([raw file](https://github.com/open-power/pnor/blob/52b1b91ea5ea7651688802f72d168139c29c4780/update_image.pl#L61)):*
<details><summary><i>Previously, sannerd wrote…</i></summary><blockquote>

Keep in mind that this same script needs to support P8 systems as well as P9.   I don't see the rest of the code handling P8?
</blockquote></details>

Sorry, but I am not aware of what needs to be done for p8.

Just copy sbe binary from hostboot directory to scratch directory, like it was done earlier?
run_command("cp $hb_binary_dir/$sbe_binary_filename $scratch_dir/");

---

*[update_image.pl, line 175 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVpPXlIUQafNsLFtyk:-KgcHgqXuhvuIbxwZ8jG:b-vlke9a) ([raw file](https://github.com/open-power/pnor/blob/529a0bac8b6ca6edc918a76c1825ce8bfc78bd18/update_image.pl#L175)):*
<details><summary><i>Previously, sannerd wrote…</i></summary><blockquote>

For future proofing, you might want to let the SBE bin output dictate the necessary EC levels?   In otherwords out of the SBE compile emit the EC levels that are required and have this script read them in?
</blockquote></details>

If I am understanding correctly, do you mean that I figure out the ec levels present - from binary itself?
May be I can grep for file names - sbe_seeprom_(.*).bin and loop through the available files?

---

*[update_image.pl, line 177 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVqv26AIkLjWgdCQQc:-KgcKdTy13FPVChwnYXw:b-iop7nc) ([raw file](https://github.com/open-power/pnor/blob/529a0bac8b6ca6edc918a76c1825ce8bfc78bd18/update_image.pl#L177)):*
<details><summary><i>Previously, wghoffa (William Hoffa) wrote…</i></summary><blockquote>

> nimbus_sbe.img

You probably need to add the EC level on to this? Otherwise aren't you going to overwrite the first EC with the second as the filenames match?
</blockquote></details>

This will be addressed as per Dean's comment on line 186, taking it out of the loop

---

*[update_image.pl, line 186 at r1](https://reviewable.io:443/reviews/open-power/pnor/61#-KgVoWP_Rgy-oyJmqmro:-KgcK7MV-MG8-hyiOxtJ:bt3wjig) ([raw file](https://github.com/open-power/pnor/blob/529a0bac8b6ca6edc918a76c1825ce8bfc78bd18/update_image.pl#L186)):*
<details><summary><i>Previously, sannerd wrote…</i></summary><blockquote>

This part should be outside of the for loop -- the buildSbePart script takes input of ALL supported EC levels for a chip and creates one PNOR partition.   Note that the SBE partition size will probably have to grow to 512K to accommodate.
</blockquote></details>

Done.
So the file 'nimbus_sbe.img' will have both ec levels in the same image?
Shall I just change 256K to 512K, or will there be any associated changes required?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/pnor/61)*

**Comment by sannerd** [comment]
Looks like you moved most of the business logic into a script provided by the SBE.  :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/pnor/61#-:-KgpPL8JDLi2_pKe3SeI:buw6vx2)*

**Comment by wghoffa** [comment]
Seems fine - but you need to squash the 3 commits into 1 commit.

**Comment by Shakeebbk** [comment]
Done. Please review.

**Comment by wghoffa** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/pnor/61)*

**Pull request merged**
