### PR TITLE
Changing the VPD sections to sideless

### PR DESCRIPTION
**Pull request by pragupta**

### CODE REVIEW

**Comment by ozbenh** [comment]
On Tue, 2015-02-24 at 06:58 -0800, Prachi Gupta wrote:
> 
> ______________________________________________________________________
> You can view, comment on, or merge this pull request online at:
>   https://github.com/open-power/pnor/pull/26

Do that mean that when booting from "golden" side, you still use the
cached VPDs ? I would object that if the VPDs are corrupted somewhat,
this would compromise the ability to recover by booting the golden side,
no ? The argument could be made that a gold side boot should not cache
the VPDs (and wipe the existing caches on the other side).

Cheers,
Ben.

**Comment by williamspatrick** [comment]
@ozbenh - we are not suppose to use the cache in golden mode.  Agree.  I think it is handled by the VPD code.

@cvswen - can you comment if that code is implemented?

**Comment by cvswen** [comment]
Dan has a change in review to clear the caches when booting from the golden side, but I don't see anything to prevent the cache from loading again.

**Comment by williamspatrick** [comment]
@dcrowell77  - Can you comment on this?  Maybe this is handled by some code from @scprek / @pragupta that prevents writes while on the golden side?

**Comment by dcrowell77** [comment]
We still need to use the pnor cache during boot or it will take an extra 2 minutes to ipl.  Also, our runtime code currently can't be enabled without the VPD caches being enabled.  I have a change pending in hostboot to wipe the cache out at the beginning of the IPL so that the next working-side boot would end up using the data cached by the golden-boot.  It would be simple enough to also wipe out our cache at the end of the boot like we do in a mfg-boot.  I'll make that change and that should take care of the issues here.

**Comment by ozbenh** [comment]
On Tue, 2015-02-24 at 20:47 -0800, Dan wrote:
> We still need to use the pnor cache during boot or it will take an
> extra 2 minutes to ipl. Also, our runtime code currently can't be
> enabled without the VPD caches being enabled. I have a change pending
> in hostboot to wipe the cache out at the beginning of the IPL so that
> the next working-side boot would end up using the data cached by the
> golden-boot. It would be simple enough to also wipe out our cache at
> the end of the boot like we do in a mfg-boot. I'll make that change
> and that should take care of the issues here.

For a golden side boot, you probably want to wipe at the beginning, ie,
so you are immune to a bad cache. Do you also want to wipe at the end
though ? Or is it ok to just keep the new "golden" cache around for
a switch back to normal side ?

Cheers,
Ben.

**Comment by dcrowell77** [comment]
It really should be okay to use the cache from the golden boot but I'm changing the code to wipe it out.

**Pull request merged**
