### PR TITLE
Create p8/p9 layout directories and add p9 layouts

### PR DESCRIPTION
**Pull request by ploetzma**
This change is [Reviewable](https://reviewable.io/reviews/open-power/pnor/51)

### CODE REVIEW

**Comment by williamspatrick** [comment]
Two comments:

1. There should be at least two commits here.  One to rearrange the P8 support into a subdirectory and one to add the P9 support.

2. Those scripts are already way past due to be rewritten.  I certainly do not want to see them duplicated.  Figure out how to add optional parameters or something so that they can be shared between P8 and P9.  (When is that code and the massively ugly script in Hostboot itself scheduled to be rewritten?)

**Comment by ploetzma** [comment]
Should the P8 directory change and P9 support be in two separate pull requests? or  two commits in this pull request fine?

**Comment by williamspatrick** [comment]
Two commits in the same pull are fine. We need to get in a habit of smaller commits with a specific purpose. Anytime your title is "and" that is a strong hint that two commits are warranted.

**Comment by stewart-ibm** [comment]
I strongly agree with @williamspatrick on all of the things here. Separate patches is much easier to review (and bisect) and these scripts are *long* past due for being retired.

https://patchwork.ozlabs.org/patch/613459/ and https://patchwork.ozlabs.org/patch/613458/ get us to a point where we could use a simple shell script with invocations of ffspart and pflash to do the same thing, and avoid horrible perl with a million fork()/exec()s to other tools.

It'd be great if we start P9 without a giant mess in how we construct flash partition layout, leaving us with just the mess that is FFS itself :)

Could we instead maybe go for the patches above plus simple shell?

**Comment by ploetzma** [comment]
@williamspatrick I have added a release parameter to the scripts so we can run the same one for p8 or p9, and broke the commit into two separate ones.

@stewart-ibm I opened up story 162073 to track this for later work.

**Comment by stewart-ibm** [comment]
Matt Ploetz <notifications@github.com> writes:
> @stewart-ibm I opened up story 162073 to track this for later work.

Where are stories on Github?

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by ploetzma** [comment]
> Where are stories on Github?

Stories are local to the hostboot team, in Rational Team Concert. I can create an issue for you to track if you would like as well

**Comment by stewart-ibm** [comment]
Matt Ploetz <notifications@github.com> writes:
>> Where are stories on Github?
>
> Stories are local to the hostboot team, in Rational Team Concert. I
> can create an issue for you to track if you would like as well

Unless it's critical to track internally (e.g. confidentiality, export
control) then tracking on github lets others see what can be done,
potentially taking on the work.

The current situation is whenever somebody has to look at PNOR
construction they start crying, so having an agreed plan up in public is
likely a good tihng.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by williamspatrick** [comment]
@stewart-ibm - While great in theory, nothing that the Hostboot team is working on is tracked outside of RTC because that is their project management tool.  Need to have an internal discussion with that team on the outlook of them transitioning their work to something public.  Ideally they would use github for issue / feature tracking and a public facing Gerrit for code.

**Pull request merged**
