### PR TITLE
Remove ECC from NVRAM partition

### PR DESCRIPTION
**Pull request by sammj**
The NVRAM partition is initialised as an ECC partition, but userspace
tools such as powerpc-utils are not ECC aware, and Skiboot
re-initialises the partition with several non-ECC partitions on boot
anyway.

Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/pnor/47)

### CODE REVIEW

**Comment by williamspatrick** [comment]
@scprek - Please review.  I thought I had assigned you this before.

**Comment by sammj** [comment]
@scprek In this patch http://patchwork.ozlabs.org/patch/643924/ Skiboot starts properly recognising the ECC flag of NVRAM. (that patch is reverted for other reasons but a v2 is incoming).
However since the data in NVRAM *isn't* actually ECC-correct, Skiboot ends up re-initialising the partition on every boot, clearing any saved settings. Can we get this PR looked at / merged before a patch like this makes it into a tagged Skiboot?

**Comment by sammj** [comment]
Aha, actually after some digging with @cyrilbur-ibm and @apopple it looks like we'll be fine to keep NVRAM marked as ECC - as long as we fix the bug in Skiboot that was just stumbled across in a different location. I'll update this PR as that is solved.

**Comment by williamspatrick** [comment]
@sammj - I did a quick review and will merge.  I don't know what is taking @scprek so long.

**Comment by ploetzma** [comment]
@sammj  - Any idea if that skiboot fix you mentioned in the note above got merged?

**Comment by ploetzma** [comment]
I think I may have found it.
https://github.com/open-power/skiboot/commit/adebaf3e0e621240c2041ed8f1ce91f70795cfa9

**Pull request merged**
