### PR TITLE
Remove the ima_catalog binary file copy command from update_*.pl file

### PR DESCRIPTION
**Pull request by maddy-kerneldev**
This change is [Reviewable](https://reviewable.io/reviews/open-power/pnor/54)

### CODE REVIEW

**Comment by ploetzma** [comment]
Why did you remove the filename variable $ima_catalog_filename and make it a constant ima_catalog.bin.ecc?

**Comment by ploetzma** [comment]
As well, if you end up removing the checks for arguments passed in, we will need a hostboot change to the create_pnor_image.pl script

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[create_pnor_image.pl, line 21 at r1](https://reviewable.io:443/reviews/open-power/pnor/54#-K_gCN5SFSjlV0HCy7v9:-K_gCN5SFSjlV0HCy7vA:b-rovl3b) ([raw file](https://github.com/open-power/pnor/blob/fb8f459cddea5113dc96ca61058565f07650d817/create_pnor_image.pl#L21)):*
> ```Prolog
> my $wink_binary_filename = "";
> my $occ_binary_filename = "";
> my $ima_catalog_filename = "";
> ```

Since you remove the variable below, this can be removed.

---

*[create_pnor_image.pl, line 90 at r1](https://reviewable.io:443/reviews/open-power/pnor/54#-K_gCYn0V3JrHRcljYbD:-K_gCYn0V3JrHRcljYbE:bh35ixh) ([raw file](https://github.com/open-power/pnor/blob/fb8f459cddea5113dc96ca61058565f07650d817/create_pnor_image.pl#L90)):*
> ```Prolog
>     }
>     elsif (/^-ima_catalog_filename/i){
>         $ima_catalog_filename = $ARGV[1] or die "Bad command line arg given: expecting ima catalog filename.\n";
> ```

As well here, since we are not passing in a catalog filename, 

---

*[update_image.pl, line 216 at r1](https://reviewable.io:443/reviews/open-power/pnor/54#-K_gDGetmt-_KbhrNzeW:-K_gDGeut9LX-b5k05DY:bd2m715) ([raw file](https://github.com/open-power/pnor/blob/fb8f459cddea5113dc96ca61058565f07650d817/update_image.pl#L216)):*
> $ima_catalog_filename 
You removed the filename variable above, but still use it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/pnor/54#-:-K_gDT8zjRJwtl4vRNJc:bsotjii)*

**Comment by maddy-kerneldev** [comment]
build script from ima-catalog repo will alway generate the output binary file as ima-catalog.bin which will include multiple catalog files. Something similar to capp-ucode package. And wanted to follow the same process here too. I can remove  "ima_catalog_filename" var create_pnor_image.pl.

Incase of update_image.pl, it is variable naming issue. I will rename it to "ima_catalog_binary_filename".
Nice catch.

**Comment by williamspatrick** [comment]
Why did you close the pull request?  You can just update the branch and the pull request will be updated.

**Pull request closed without merging**
