### PR TITLE
Add 1MB to HBI PNOR section

### PR DESCRIPTION
**Pull request by milesg-github**
Hostboot binary size is getting close to limit so adding 1MB.

### CODE REVIEW

**Comment by sammj** [comment]
Didn't this already happen in https://github.com/open-power/pnor/commit/83af072323e88fd8d4be6f71fd9c6f5d778e6edf?

**Comment by milesg-github** [comment]
This is adding an additional 1MB on top of what 83af072 added.

**Comment by sammj** [comment]
OK, what is the extra 1MB needed for?

**Comment by dcrowell77** [comment]
We have a bunch of new code going in for FW930 and Axone that have made us exceed the allocated space.  We also recently enabled support for thread_local variables which added a tax on each of our modules.

**Pull request merged**
